# 16) Crea un array numpy di dimensione 3x3 con valori casuali.

In [3]:
import numpy as np

matrice_3_x_3 = np.random.randint(1, 100, size=(3, 3))

print(matrice_3_x_3)


[[ 2  2 57]
 [90 87 21]
 [88 64 96]]


# 17) Scrivi un programma che calcoli la somma di tutti gli elementi in un array numpy.

In [11]:
import numpy as np

lista_numerica = [23, 56, 12, 7, 45, 99, 33, 18, 5, 72]
array_numerico = np.array(lista_numerica)

somma_array= np.sum(array_numerico)
somma_array


370

# 18) Crea un array numpy e calcolane la media, mediana e varianza.

In [17]:
import numpy as np

lista_numerica_2 = [8, 31, 60, 14, 92, 27, 50, 9, 42, 67]
array_numerico_2 = np.array(lista_numerica_2)

media_array = np.mean(array_numerico_2)
print(f"La media è di: {media_array}")

mediana_array =np.median(array_numerico_2)
print(f"La mediana è di: {mediana_array}")

varianza_array = np.var(array_numerico_2)
print(f"La varianza è di: {varianza_array}")

La media è di: 40.0
La mediana è di: 36.5
La varianza è di: 684.8


# 19) Scrivi un programma che moltiplichi due matrici numpy.

In questo esempio, abbiamo definito due matrici numpy matrice1 e matrice2. 
Poi abbiamo utilizzato la funzione np.dot() per eseguire la moltiplicazione tra le due matrici e memorizzarla nella variabile risultato. 
Infine, abbiamo stampato le matrici di input e il risultato della moltiplicazione.

In [24]:
# Moltiplicazione tra matrici
import numpy as np

matrice1 = np.array([[1, 2], [3, 4]])
matrice2 = np.array([[5, 6], [7, 8]])

risultato = np.dot(matrice1, matrice2)

print("Matrice 1:")
print(matrice1)

print("\nMatrice 2:")
print(matrice2)

print("\nRisultato della moltiplicazione:")
print(risultato)


Matrice 1:
[[1 2]
 [3 4]]

Matrice 2:
[[5 6]
 [7 8]]

Risultato della moltiplicazione:
[[19 22]
 [43 50]]


In [28]:
# Moltiplicazione tra array
import numpy as np

lista1 = [10, 2, 35, 49, 5]
lista2 = [64, 71, 82, 9, 10]

array1 = np.array(lista1)
array2 = np.array(lista2)

risultato_elemento_per_elemento = array1 * array2

risultato = np.dot(array1, array2)

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nRisultato della moltiplicazione elemento per elemento:")
print(risultato_elemento_per_elemento)

print("\nRisultato della moltiplicazione complessiva:")
print(risultato)

Array 1:
[10  2 35 49  5]

Array 2:
[64 71 82  9 10]

Risultato della moltiplicazione:
4143

Risultato della moltiplicazione elemento per elemento:
[ 640  142 2870  441   50]


# 20) Crea un array numpy e ordinalo in modo ascendente.

In [25]:
lista_numerica_3 = [42, 88, 15, 76, 5, 61, 29, 11, 37, 93]
array_numerico_3 = np.array(lista_numerica_3)
print("L'array non ordinato è: ",  array_numerico_3)

array_ordinato_asc = np.sort(array_numerico_3)
print("L'array ordinato è: ",  array_ordinato_asc)


L'array non ordinato è:  [42 88 15 76  5 61 29 11 37 93]
L'array ordinato è:  [ 5 11 15 29 37 42 61 76 88 93]
